// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDpvNwvX-h-j_ZhnxzUBl-HtIjrKgj1iI',
    appId: '1:491584381634:web:8f7c830bb34add9084515b',
    messagingSenderId: '491584381634',
    projectId: 'gozunarkadakalmasin',
    authDomain: 'gozunarkadakalmasin.firebaseapp.com',
    storageBucket: 'gozunarkadakalmasin.firebasestorage.app',
    measurementId: 'G-Q7Y1GM8WGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqaO5S0FC0xl65Wd4CfE8cULEl6jWYx5Y',
    appId: '1:491584381634:android:bcd28268fadfcc4984515b',
    messagingSenderId: '491584381634',
    projectId: 'gozunarkadakalmasin',
    storageBucket: 'gozunarkadakalmasin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTbO2zBYvAC-AGjVVmz7KefohyTDcQ_S4',
    appId: '1:491584381634:ios:cdda36c1d743e77084515b',
    messagingSenderId: '491584381634',
    projectId: 'gozunarkadakalmasin',
    storageBucket: 'gozunarkadakalmasin.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTbO2zBYvAC-AGjVVmz7KefohyTDcQ_S4',
    appId: '1:491584381634:ios:cdda36c1d743e77084515b',
    messagingSenderId: '491584381634',
    projectId: 'gozunarkadakalmasin',
    storageBucket: 'gozunarkadakalmasin.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDpvNwvX-h-j_ZhnxzUBl-HtIjrKgj1iI',
    appId: '1:491584381634:web:95bf057611f1a92484515b',
    messagingSenderId: '491584381634',
    projectId: 'gozunarkadakalmasin',
    authDomain: 'gozunarkadakalmasin.firebaseapp.com',
    storageBucket: 'gozunarkadakalmasin.firebasestorage.app',
    measurementId: 'G-KRDSTDZEN5',
  );
}
