name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_contacts: ^1.1.9+2
  geolocator: ^14.0.2
  
  # Modern ve Sorunsuz Ses Algılama Paketleri
  permission_handler: any
  speech_to_text: any
  pitch_detector_dart: any
  record: any
  path_provider: ^2.1.5
  telephony: ^0.2.0
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\el_arka_plan.png